config_version = "0"

test_patterns = ["packages/**/test/*.ts"]

[[source]]
name = "default"
default = true

[[plugin]]
name = "eslint"

[smells.file_complexity]
threshold = 1000

[smells.function_complexity]
threshold = 30

[smells.return_statements]
threshold = 20

[smells.similar_code]
enabled = true

[smells.identical_code]
enabled = true

[language.javascript.smells.similar_code]
enabled = true
threshold = 60

[language.typescript.smells.similar_code]
enabled = true
threshold = 60
